variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - prepare_develop_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    before_script:
        - dpkg --add-architecture armhf
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20200718/debian stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install crossbuild-essential-armhf libc6-dev:armhf cpio -y --allow-unauthenticated
        - apt-get build-dep -y ./
    script:
        - dpkg-buildpackage -us -uc -b -aarmhf
        - dpkg-buildpackage -us -uc -b
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - 4.4.190-cip36-rt25/stretch/master
    dependencies:
        - develop_build
    when: manual
    script:
        - mkdir -p /cache/stretch/mil-internal-release/
        - cp *.deb /cache/stretch/mil-internal-release/
        - ls /cache/stretch/mil-internal-release/
