variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - release_build
    - prepare_develop_debs
    - prepare_release_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    except:
      refs:
        - 4.4.154-cip/stretch
    only:
      variables:
        - $model
    script:
        - dpkg --add-architecture armhf
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20180717 stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install crossbuild-essential-armhf libc6-dev:armhf cpio -y --allow-unauthenticated
        - dpkg-buildpackage -us -uc -b -aarmhf
        - dpkg-buildpackage -us -uc -b
        - mv ../linux*.deb .
        - mv ../"${model}"*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb

release_build:
    tags:
        - Runner-Stretch
    stage: release_build
    only:
      refs:
        - 4.4.154-cip/stretch
      variables:
        - $model
    script:
        - dpkg --add-architecture armhf
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20180717 stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install crossbuild-essential-armhf libc6-dev:armhf cpio -y --allow-unauthenticated
        - dpkg-buildpackage -us -uc -b -aarmhf
        - dpkg-buildpackage -us -uc -b
        - mv ../linux*.deb .
        - mv ../"${model}"*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - 4.4.154-cip/stretch-develop
    dependencies:
        - develop_build
    when: manual
    script:
        - mkdir -p /cache/stretch/develop/
        - cp *.deb /cache/stretch/develop/
        - ls /cache/stretch/develop/

prepare_release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_release_debs
    only:
      refs:
        - 4.4.154-cip/stretch
    when: manual
    dependencies:
        - release_build
    script:
        - mkdir -p /cache/stretch/release/
        - cp *.deb /cache/stretch/release/
        - ls /cache/stretch/release/
